### ISSUE TITLE
我想问一下关于定时同步的问题

### ISSUE THREAD

**Issue by mxue12138** [zencodex/composer-mirror#5]
前提：我们是一家php教育机构，我们想用您这个镜像来部署到我们自己的服务器上，用以学校内部和教职员工使用，这样既能降低你们的压力，我们也能使用更方便。

问题：因为我们服务器已经上线使用了，所以在没有测试的情况下不能随便上线，我想问一下如果使用您的同步服务，2核4G内存200M带宽（按量计费）的服务器是否足够？同时一次同步大概能消耗多少流量和多长时间呢？

**Comment by zencodex** [comment]
配置够用，存储空间最好预留3T
目前 zip 包还不支持本地存，我今天尽量加上，还有其他校园镜像也需要

**Comment by zencodex** [comment]
更新最新的代码，支持zip包存储到本地，方法：
修改 config.php，使用 NullAdapter 

    'cloudDisk' => (object)[
        'adapter' => 'League\\Flysystem\\Adapter\\NullAdapter',
